version: '3.8'
services:
  postgres:
    image: postgres:15
    #restart: always
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=redwood
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    command: postgres -c max_locks_per_transaction=512
  # redis:
  #   image: redis/redis-stack-server
  #   command: redis-server --requirepass ${REDIS_PASSWORD}
  #   ports:
  #     - "6379:6379"
volumes:
  postgres:
